name: Deploy to Streamlit Cloud

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_streamlit.txt

      - name: Run tests
        run: |
          # Add any tests you want to run before deployment
          echo "Running tests..."
          python -c "import streamlit; print('Streamlit import successful')"

      - name: Deploy to Streamlit Cloud
        run: |
          echo "Deployment triggered. Please ensure Streamlit Cloud is set to auto-deploy from the main branch."